"""empty message

Revision ID: 04d951f70bed
Revises: 5fda3dd79dce
Create Date: 2022-12-12 00:06:35.294178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d951f70bed'
down_revision = '5fda3dd79dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('remarks', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'cookies', ['remarks'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cookies', type_='unique')
    op.drop_column('cookies', 'remarks')
    # ### end Alembic commands ###
