"""empty message

Revision ID: 222559e4b2af
Revises: 843a6ca15c99
Create Date: 2022-12-12 16:57:41.499687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '222559e4b2af'
down_revision = '843a6ca15c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookies', 'convertibility')
    op.drop_column('cookies', 'past_due')
    op.drop_index('qq', table_name='cookies_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('qq', 'cookies_log', ['qq'], unique=False)
    op.add_column('cookies', sa.Column('past_due', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('cookies', sa.Column('convertibility', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
