"""empty message

Revision ID: 5c257b802a73
Revises: 838fceac35e1
Create Date: 2023-01-11 17:39:34.382360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c257b802a73'
down_revision = '838fceac35e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_date', sa.String(length=100), nullable=True),
    sa.Column('update_url', sa.String(length=500), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_log')
    # ### end Alembic commands ###
