"""empty message

Revision ID: 70d4a96cf5d8
Revises: 5c257b802a73
Create Date: 2023-12-26 15:41:07.742085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70d4a96cf5d8'
down_revision = '5c257b802a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_log', sa.Column('update_id', sa.String(length=100), nullable=True))
    op.drop_column('update_log', 'update_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_log', sa.Column('update_url', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('update_log', 'update_id')
    # ### end Alembic commands ###
