"""empty message

Revision ID: 838fceac35e1
Revises: 74577572e8b8
Create Date: 2022-12-17 18:05:14.419462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '838fceac35e1'
down_revision = '74577572e8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('states', sa.Integer(), nullable=True))
    op.alter_column('cookies_log', 'states',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cookies_log', 'states',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('cookies', 'states')
    # ### end Alembic commands ###
