"""empty message

Revision ID: 8f2d22c25c04
Revises: 222559e4b2af
Create Date: 2022-12-12 19:55:05.048434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2d22c25c04'
down_revision = '222559e4b2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('remarks', table_name='cookies_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('remarks', 'cookies_log', ['remarks'], unique=False)
    # ### end Alembic commands ###
