"""empty message

Revision ID: e303d3a9ca0f
Revises: 8f2d22c25c04
Create Date: 2022-12-12 20:28:22.878697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e303d3a9ca0f'
down_revision = '8f2d22c25c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('type', sa.Integer(), nullable=True))
    op.add_column('cookies_log', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookies_log', 'type')
    op.drop_column('cookies', 'type')
    # ### end Alembic commands ###
