"""empty message

Revision ID: fc6e98491798
Revises: 
Create Date: 2022-12-10 23:55:07.178920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc6e98491798'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('flag', sa.Integer(), nullable=True))
    op.alter_column('cookies', 'qq',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cookies', 'url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('cookies', 'headers',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    op.alter_column('cookies', 'data',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'cookies', ['qq'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cookies', type_='unique')
    op.alter_column('cookies', 'data',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.alter_column('cookies', 'headers',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.alter_column('cookies', 'url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('cookies', 'qq',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('cookies', 'flag')
    # ### end Alembic commands ###
